export const ActionTypes = {
    SET_NOTES: "SET_NOTES",
    SET_FILTERED_NOTES: "SET_FILTERED_NOTES",
    ADD_NEW_NOTE:"ADD_NEW_NOTE",
    UPDATE_NOTE:"UPDATE_NOTE",
    SET_TRASH_NOTES:"SET_TRASH_NOTES",
    ADD_TRASH_NOTE:"ADD_TRASH_NOTE",
    RESTORE_FROM_TRASH:"RESTORE_FROM_TRASH",
    DELETE_FROM_TRASH:"DELETE_FROM_TRASH",
    LIST_VIEW:"LIST_VIEW",
    EMPTY_TRASH:"EMPTY_TRASH",
  };